# Generated by Django 4.1.2 on 2022-10-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='sub_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_question', to='apps.subcategory'),
            preserve_default=False,
        ),
    ]
