# Generated by Django 4.1.2 on 2022-10-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_questions_sub_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_answer',
            field=models.CharField(default='answer1', max_length=255),
        ),
    ]
