# Generated by Django 4.1.2 on 2022-10-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryuser',
            name='sub_category_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cat', to='apps.subcategory'),
        ),
        migrations.AlterField(
            model_name='categoryuser',
            name='yalnysh_jogap',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
