# Generated by Django 4.1.2 on 2022-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_categoryuser_sub_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
