# Generated by Django 4.1.2 on 2022-10-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_questions_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='desc',
            field=models.ImageField(blank=True, null=True, upload_to='description'),
        ),
    ]
