# Generated by Django 4.1.2 on 2022-10-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_questions_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='desc',
        ),
    ]
