# Generated by Django 4.1.2 on 2022-10-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_questions_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='description',
        ),
    ]
